# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35fe43d25907d579c7e93c33ed1e678b4d40362f7e3a8e701d9c50d5d4fa0938a23ec8788f10a22460c1543cb14c2058af2211d9ef64f00a50d5e123f2f47768

test:
  secret_key_base: 9ec11522d4c260382c29cfb09ec2c36e58acccc642f7be211b1ac64ed8d61197fec314dd5ae6061152d521aca03a766334ac93597a5d29961e40575e1d8b782b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
